require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - db/schema.rb
    - db/seeds.rb
    - vendor/bundle/**/*

Style/MixinUsage:
  Include:
    - app/**/*.rb

Style/Documentation:
  Enabled: false

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 50

