require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - db/schema.rb
    - db/seeds.rb
    - vendor/bundle/**/*

# environmentつけない処理を行うこともあるため
Rails/RakeEnvironment:
  Enabled: false

# expectが複数行並ぶケースがあるので、ExampleLengthは考慮しない
RSpec/ExampleLength:
  Enabled: false

# aggregate_failures を有効にしたいので複数のexpectを許可する
RSpec/MultipleExpectations:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/environments/*.rb
    - config/routes.rb
    - db/migrate/*.rb
    - spec/**/*.rb

