version: '3'
services:
  web:
    tty: true
    stdin_open: true
    build: .
    ports:
      - 3000:3000
    volumes:
      - "./:/work:cached"
      - "./vendor/bundle:/bundle:cached"
      #- /work/vendor/bundle
      - /work/.git
    depends_on:
      - db
  db:
    image: postgres:11-alpine
    volumes:
      - "pg_data:/var/lib/postgresql/data"

volumes:
  pg_data:
