swagger: "2.0"
consumes:
  - application/json
produces:
  - application/json
info:
  description: "userサンプルAPI"
  version: "1.0.0"
  title: "User API"
paths:
  /users:
    get:
      summary: "user一覧API"
      responses:
        200:
          description: "成功時のレスポンス"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/User"
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
        example: "doggie"

